// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type ChallengeRequired = {
    challenge_id: string;
    destination: string;
};

/**
 * Authenticate with email + password; optionally defer JWT for 2FA.
 */
export type EmailTokenObtain = {
    email: string;
    password: string;
};

export type ForgotPassword = {
    email: string;
};

export type Logout = {
    refresh: string;
};

export type Me = {
    readonly id: number;
    email: string;
    readonly permissions: Array<string>;
};

export type PaginatedUserList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<User>;
};

export type PatchedUserUpdate = {
    readonly id?: number;
    email?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
};

export type ResendCode = {
    challenge_id: string;
};

export type ResetPassword = {
    email: string;
    code: string;
};

export type TokenPair = {
    access: string;
    refresh: string;
};

export type TokenRefresh = {
    readonly access: string;
    refresh: string;
};

export type User = {
    readonly id: number;
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
    /**
     * Superuser status
     *
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly is_superuser: boolean;
    readonly created: string;
    readonly modified: string;
    readonly last_login: string | null;
};

export type UserCreate = {
    readonly id: number;
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
};

export type UserUpdate = {
    readonly id: number;
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
};

export type VerifyCode = {
    challenge_id: string;
    code: string;
};

export type MeWritable = {
    email: string;
};

export type PaginatedUserListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<UserWritable>;
};

export type PatchedUserUpdateWritable = {
    email?: string;
    password?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
};

export type ResetPasswordWritable = {
    email: string;
    code: string;
    new_password: string;
    confirm_password: string;
};

export type TokenRefreshWritable = {
    refresh: string;
};

export type UserWritable = {
    email: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
};

export type UserCreateWritable = {
    email: string;
    password: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
};

export type UserUpdateWritable = {
    email: string;
    password?: string;
    /**
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
    /**
     * Designates whether the user can log into the admin site.
     */
    is_staff?: boolean;
};

export type AuthForgotPasswordCreateData = {
    body: ForgotPassword;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgot-password/';
};

export type AuthForgotPasswordCreateResponses = {
    /**
     * Always empty (anti-enumeration).
     */
    204: void;
};

export type AuthForgotPasswordCreateResponse = AuthForgotPasswordCreateResponses[keyof AuthForgotPasswordCreateResponses];

export type AuthLogoutCreateData = {
    body: Logout;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout/';
};

export type AuthLogoutCreateResponses = {
    200: Logout;
};

export type AuthLogoutCreateResponse = AuthLogoutCreateResponses[keyof AuthLogoutCreateResponses];

export type AuthMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me/';
};

export type AuthMeRetrieveResponses = {
    200: Me;
};

export type AuthMeRetrieveResponse = AuthMeRetrieveResponses[keyof AuthMeRetrieveResponses];

export type AuthResendCodeCreateData = {
    body: ResendCode;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resend-code/';
};

export type AuthResendCodeCreateResponses = {
    200: ChallengeRequired;
};

export type AuthResendCodeCreateResponse = AuthResendCodeCreateResponses[keyof AuthResendCodeCreateResponses];

export type AuthResetPasswordCreateData = {
    body: ResetPasswordWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/reset-password/';
};

export type AuthResetPasswordCreateResponses = {
    /**
     * Password updated.
     */
    204: void;
};

export type AuthResetPasswordCreateResponse = AuthResetPasswordCreateResponses[keyof AuthResetPasswordCreateResponses];

export type AuthTokenCreateData = {
    body: EmailTokenObtain;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token/';
};

export type AuthTokenCreateResponses = {
    /**
     * JWT pair when LOGIN_2FA_ENABLED is false.
     */
    200: TokenPair;
    /**
     * 2FA challenge when LOGIN_2FA_ENABLED is true.
     */
    202: ChallengeRequired;
};

export type AuthTokenCreateResponse = AuthTokenCreateResponses[keyof AuthTokenCreateResponses];

export type AuthTokenRefreshCreateData = {
    body: TokenRefreshWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/token/refresh/';
};

export type AuthTokenRefreshCreateResponses = {
    200: TokenRefresh;
};

export type AuthTokenRefreshCreateResponse = AuthTokenRefreshCreateResponses[keyof AuthTokenRefreshCreateResponses];

export type AuthVerifyCodeCreateData = {
    body: VerifyCode;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify-code/';
};

export type AuthVerifyCodeCreateResponses = {
    200: TokenPair;
};

export type AuthVerifyCodeCreateResponse = AuthVerifyCodeCreateResponses[keyof AuthVerifyCodeCreateResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A search term.
         */
        search?: string;
    };
    url: '/api/v1/users/';
};

export type UsersListResponses = {
    200: PaginatedUserList;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: UserCreateWritable;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateResponses = {
    201: UserCreate;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUserUpdateWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: UserUpdate;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: UserUpdateWritable;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/users/{id}/';
};

export type UsersUpdateResponses = {
    200: UserUpdate;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];
